### ISSUE TITLE
Server master panic when allocateTasks with no available executors

### ISSUE THREAD

**Issue by amyangfei** [hanfei1991/microcosm#122]
```golang
panic: runtime error: index out of range [0] with length 0

goroutine 580 [running]:
github.com/hanfei1991/microcosm/servermaster/resource.(*CapRescMgr).allocateTasksWithNaiveStrategy(0xc0006961e0, {0xc000498510, 0x1, 0x40b66d})
	/home/zixiong/microcosm/servermaster/resource/capacity_impl.go:89 +0x2ec
github.com/hanfei1991/microcosm/servermaster/resource.(*CapRescMgr).Allocate(0x10ed380, {0xc000498510, 0x0, 0xc000f84860})
	/home/zixiong/microcosm/servermaster/resource/capacity_impl.go:50 +0x1e
github.com/hanfei1991/microcosm/servermaster.(*ExecutorManagerImpl).Allocate(0x40c8c5, {0xc000498510, 0x11dfa00, 0x0})
	/home/zixiong/microcosm/servermaster/executor_manager.go:151 +0x27
github.com/hanfei1991/microcosm/servermaster.(*Server).ScheduleTask(0xc000f84890, {0xc98cbb, 0xc000ed9ec0}, 0xc000ed9ef0)
	/home/zixiong/microcosm/servermaster/server.go:217 +0x4f
```

**Comment by amyangfei** [comment]
Fixed by https://github.com/hanfei1991/microcosm/pull/123
