### ISSUE TITLE
p2p package panic

### ISSUE THREAD

**Issue by hanfei1991** [hanfei1991/microcosm#268]
log:

```
[2022/03/29 12:24:33.951 +08:00] [WARN] [server.go:262] ["handler not found"] [topic=worker-status-change-req-3086a1b0-2397-4f5a-8dd0-971acdd4ce40-22949035-aea9-4dfa-b696-7e77b8b3e468][2022/03/29 12:24:33.957 +08:00] [WARN] [server.go:438] ["topic handler returned error"] [error="[CDC:ErrWorkerPoolHandleCancelled]workerpool handle is cancelled"] [errorVerbose="[CDC:ErrWorkerPoolHandleCancelled]workerpool handle is cancelled\ngithub.com/pingcap/errors.AddStack\n\t/root/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\t/root/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/pkg/workerpool.(*defaultEventHandle).GracefulUnregister.func1\n\t/root/go/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220308162507-e342c02e789c/pkg/workerpool/pool_impl.go:201\ngithub.com/pingcap/tiflow/pkg/workerpool.(*defaultEventHandle).GracefulUnregister\n\t/root/go/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220308162507-e342c02e789c/pkg/workerpool/pool_impl.go:223\ngithub.com/pingcap/tiflow/pkg/p2p.(*MessageServer).run.func2\n\t/root/go/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220308162507-e342c02e789c/pkg/p2p/server.go:240\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1571"][2022/03/29 12:24:33.958 +08:00] [WARN] [server.go:262] ["handler not found"] [topic=heartbeat-pong-3086a1b0-2397-4f5a-8dd0-971acdd4ce40-fba7af79-d910-4aea-9974-4bfcb3c34b68][2022/03/29 12:24:33.958 +08:00] [WARN] [server.go:438] ["topic handler returned error"] [error="[CDC:ErrWorkerPoolHandleCancelled]workerpool handle is cancelled"] [errorVerbose="[CDC:ErrWorkerPoolHandleCancelled]workerpool handle is cancelled\ngithub.com/pingcap/errors.AddStack\n\t/root/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\t/root/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/pkg/workerpool.(*defaultEventHandle).GracefulUnregister.func1\n\t/root/go/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220308162507-e342c02e789c/pkg/workerpool/pool_impl.go:201\ngithub.com/pingcap/tiflow/pkg/workerpool.(*defaultEventHandle).GracefulUnregister\n\t/root/go/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220308162507-e342c02e789c/pkg/workerpool/pool_impl.go:223\ngithub.com/pingcap/tiflow/pkg/p2p.(*MessageServer).run.func2\n\t/root/go/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220308162507-e342c02e789c/pkg/p2p/server.go:240\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1571"][2022/03/29 12:24:33.959 +08:00] [WARN] [server.go:438] ["topic handler returned error"] [error="[CDC:ErrWorkerPoolHandleCancelled]workerpool handle is cancelled"] [errorVerbose="[CDC:ErrWorkerPoolHandleCancelled]workerpool handle is cancelled\ngithub.com/pingcap/errors.AddStack\n\t/root/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\t/root/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/pkg/workerpool.(*defaultEventHandle).GracefulUnregister.func1\n\t/root/go/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220308162507-e342c02e789c/pkg/workerpool/pool_impl.go:201\ngithub.com/pingcap/tiflow/pkg/workerpool.(*defaultEventHandle).GracefulUnregister\n\t/root/go/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220308162507-e342c02e789c/pkg/workerpool/pool_impl.go:223\ngithub.com/pingcap/tiflow/pkg/p2p.(*MessageServer).run.func2\n\t/root/go/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220308162507-e342c02e789c/pkg/p2p/server.go:240\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1571"][2022/03/29 12:24:33.959 +08:00] [WARN] [server.go:438] ["topic handler returned error"] [error="[CDC:ErrWorkerPoolHandleCancelled]workerpool handle is cancelled"] [errorVerbose="[CDC:ErrWorkerPoolHandleCancelled]workerpool handle is cancelled\ngithub.com/pingcap/errors.AddStack\n\t/root/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\t/root/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/pkg/workerpool.(*defaultEventHandle).GracefulUnregister.func1\n\t/root/go/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220308162507-e342c02e789c/pkg/workerpool/pool_impl.go:201\ngithub.com/pingcap/tiflow/pkg/workerpool.(*defaultEventHandle).GracefulUnregister\n\t/root/go/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220308162507-e342c02e789c/pkg/workerpool/pool_impl.go:223\ngithub.com/pingcap/tiflow/pkg/p2p.(*MessageServer).run.func2\n\t/root/go/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220308162507-e342c02e789c/pkg/p2p/server.go:240\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1571"][2022/03/29 12:24:33.960 +08:00] [PANIC] [server.go:498] ["duplicate handlers"] [topic=heartbeat-pong-dataflow-engine-job-manager-d3099c99-dcc2-44c2-bfd4-811496faf9f2] [stack="github.com/pingcap/tiflow/pkg/p2p.(*MessageServer).registerHandler\n\t/root/go/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220308162507-e342c02e789c/pkg/p2p/server.go:498\ngithub.com/pingcap/tiflow/pkg/p2p.(*MessageServer).run\n\t/root/go/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220308162507-e342c02e789c/pkg/p2p/server.go:231\ngithub.com/pingcap/tiflow/pkg/p2p.(*MessageServer).Run.func2\n\t/root/go/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220308162507-e342c02e789c/pkg/p2p/server.go:194\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/root/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57"]

**panic: duplicate handlers                                                                                                                                     goroutine 291 [running]:go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc05819d200, {0xc09e282280, 0x1, 0x1})                                                                                 /root/go/pkg/mod/go.uber.org/zap@v1.20.0/zapcore/entry.go:232 +0x44cgo.uber.org/zap.(*Logger).Panic(0xc00019e7e0?, {0x44089bf?, 0x1?}, {0xc09e282280, 0x1, 0x1})        /root/go/pkg/mod/go.uber.org/zap@v1.20.0/logger.go:230 +0x59github.com/pingcap/log.Panic({0x44089bf, 0x12}, {0xc09e282280, 0x1, 0x1})        /root/go/pkg/mod/github.com/pingcap/log@v0.0.0-20211215031037-e024ba4eb0ee/global.go:54 +0x10cgithub.com/pingcap/tiflow/pkg/p2p.(*MessageServer).registerHandler(0xc000aad200, {0x4b19188, 0xc000798080}, {0xc035276730, 0x4f}, {0x4b25890?, 0xc0690744d0}, 0x11?)        /root/go/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220308162507-e342c02e789c/pkg/p2p/server.go:498 +0x19cgithub.com/pingcap/tiflow/pkg/p2p.(*MessageServer).run(0xc000aad200, {0x4b19188?, 0xc000798080})        /root/go/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220308162507-e342c02e789c/pkg/p2p/server.go:231 +0x4c5github.com/pingcap/tiflow/pkg/p2p.(*MessageServer).Run.func2()        /root/go/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220308162507-e342c02e789c/pkg/p2p/server.go:194 +0x25golang.org/x/sync/errgroup.(*Group).Go.func1()        /root/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67created by golang.org/x/sync/errgroup.(*Group).Go                                                                                                                     /root/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d**
```

**Comment by liuzix** [comment]
This issue seems related to #267
