### ISSUE TITLE
IsMasterReady returns true but some OnWorkerOnline are not triggered yet

### ISSUE THREAD

**Issue by amyangfei** [hanfei1991/microcosm#325]
Similar steps in #322 to reproduce

- Start three server masters, one executor
- Submit one demo job
- Kill the leader of server master
- After a while, the new elected server master leader will panic

```go
[2022/04/21 11:18:34.431 +08:00] [INFO] [master.go:287] ["Heartbeat Ping received"] [msg="{\"send-time\":220259750287387,\"from-worker-id\":\"5f5ad64b-1986-4a0a-a088-cf192b3c8d35\",\"epoch\":460}"] [master-id=dataflow-engine-job-manager]
[2022/04/21 11:18:34.435 +08:00] [INFO] [worker_manager.go:227] ["Worker discovered"] [master-id=dataflow-engine-job-manager] [worker-entry="{worker-id:5f5ad64b-1986-4a0a-a088-cf192b3c8d35, executor-id:, state:1}"]
[2022/04/21 11:18:34.435 +08:00] [INFO] [worker_manager.go:240] ["All workers have sent heartbeats, sending signal to resume the master"] [master-id=dataflow-engine-job-manager]
[2022/04/21 11:18:34.435 +08:00] [INFO] [worker_manager.go:181] ["All workers have sent heartbeats after master failover. Resuming right now."] [duration=5.504040075s]
[2022/04/21 11:18:34.448 +08:00] [INFO] [jobmanager.go:267] ["recover job, move it to WaitAck job queue"] [job="{\"id\":\"5f5ad64b-1986-4a0a-a088-cf192b3c8d35\",\"addr\":\"127.0.0.1:12302\",\"node-id\":\"34fd468d-306b-4ea3-87aa-eec40939578e\",\"epoch\":445,\"status\":2,\"type\":3,\"config\":\"ewogICAgImpvYi1uYW1lIjogInRlc3QtZmFrZS1qb2ItMSIsCiAgICAid29ya2VyLWNvdW50IjogNCwKICAgICJ0YXJnZXQtdGljayI6IDMwMDAKfQo=\"}"]
[2022/04/21 11:18:34.707 +08:00] [INFO] [executor_manager.go:91] ["handle heart beat"] [req="executor_id:\"34fd468d-306b-4ea3-87aa-eec40939578e\" status:1 timestamp:1650511114 ttl:23000 "]
[2022/04/21 11:18:35.208 +08:00] [INFO] [server.go:140] [payload="executor_id:\"34fd468d-306b-4ea3-87aa-eec40939578e\" status:1 timestamp:1650511115 ttl:23000 "] [request=Heartbeat]
[2022/04/21 11:18:35.273 +08:00] [INFO] [jobmanager.go:310] ["on worker status updated"] [worker-id=5f5ad64b-1986-4a0a-a088-cf192b3c8d35] [status="{\"code\":1,\"error-message\":\"\",\"ext-bytes\":\"eyIxMmY3ZjU3ZC05YTVjLTQzZjItODRlZi1jZDFhN2MyNWViMDciOjM1NywiNjE5MWVkYzAtZWI0NC00MDk4LWJmYmYtNDM5ODE3MzlhMzNiIjozNTUsIjYyY2U2ZjFhLWU0MTctNDY2OS1hNmZhLTg0NDYwOGI2OTljZCI6MzU1LCJjNDIwMWYxMi0wMjVkLTQ3YmYtYmE1ZS1hMmU5ZDFjYTNhYjYiOjM1NX0=\"}"]
[2022/04/21 11:18:35.273 +08:00] [INFO] [master.go:489] [CreateWorker] [worker-type=3] [worker-config="{\"id\":\"5f5ad64b-1986-4a0a-a088-cf192b3c8d35\",\"addr\":\"127.0.0.1:12302\",\"node-id\":\"34fd468d-306b-4ea3-87aa-eec40939578e\",\"epoch\":445,\"status\":2,\"type\":3,\"config\":\"ewogICAgImpvYi1uYW1lIjogInRlc3QtZmFrZS1qb2ItMSIsCiAgICAid29ya2VyLWNvdW50IjogNCwKICAgICJ0YXJnZXQtdGljayI6IDMwMDAKfQo=\"}"] [master-id=dataflow-engine-job-manager]
[2022/04/21 11:18:35.273 +08:00] [INFO] [job_fsm.go:208] ["tombstone job master doesn't receive heartbeat in time, recreate it"] [job="{\"WorkerHandle\":null,\"id\":\"5f5ad64b-1986-4a0a-a088-cf192b3c8d35\",\"addr\":\"127.0.0.1:12302\",\"node-id\":\"34fd468d-306b-4ea3-87aa-eec40939578e\",\"epoch\":445,\"status\":2,\"type\":3,\"config\":\"ewogICAgImpvYi1uYW1lIjogInRlc3QtZmFrZS1qb2ItMSIsCiAgICAid29ya2VyLWNvdW50IjogNCwKICAgICJ0YXJnZXQtdGljayI6IDMwMDAKfQo=\"}"]
[2022/04/21 11:18:35.275 +08:00] [PANIC] [worker_manager.go:317] ["worker already exists"] [worker-id=5f5ad64b-1986-4a0a-a088-cf192b3c8d35] [stack="github.com/hanfei1991/microcosm/lib/master.(*WorkerManager).OnCreatingWorker\n\t/home/apple/work/code/microcosm/lib/master/worker_manager.go:317\ngithub.com/hanfei1991/microcosm/lib.(*DefaultBaseMaster).CreateWorker.func1\n\t/home/apple/work/code/microcosm/lib/master.go:533"]
panic: worker already exists

goroutine 1076 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc001c9da40, {0xc000563e80, 0x1, 0x1})
        /home/apple/.gvm/pkgsets/go1.18/global/pkg/mod/go.uber.org/zap@v1.21.0/zapcore/entry.go:232 +0x44c
go.uber.org/zap.(*Logger).Panic(0x1b006e0?, {0x1e3abca?, 0xc000a231a0?}, {0xc000563e80, 0x1, 0x1})
        /home/apple/.gvm/pkgsets/go1.18/global/pkg/mod/go.uber.org/zap@v1.21.0/logger.go:230 +0x59
github.com/hanfei1991/microcosm/lib/master.(*WorkerManager).OnCreatingWorker(0xc0021069c0, {0xc000a231a0, 0x24}, {0xc000a23710, 0x24})
        /home/apple/work/code/microcosm/lib/master/worker_manager.go:317 +0x1fa
github.com/hanfei1991/microcosm/lib.(*DefaultBaseMaster).CreateWorker.func1()
        /home/apple/work/code/microcosm/lib/master.go:533 +0x3ba
created by github.com/hanfei1991/microcosm/lib.(*DefaultBaseMaster).CreateWorker
        /home/apple/work/code/microcosm/lib/master.go:506 +0x638
```

- We can notice heartbeat of a job master is received `[2022/04/21 11:18:34.431 +08:00] [INFO] [master.go:287] ["Heartbeat Ping received"] [msg="{\"send-time\":220259750287387,\"from-worker-id\":\"5f5ad64b-1986-4a0a-a088-cf192b3c8d35\",\"epoch\":460}"] [master-id=dataflow-engine-job-manager]`
- worker manager marks ready `[2022/04/21 11:18:34.435 +08:00] [INFO] [worker_manager.go:181] ["All workers have sent heartbeats after master failover. Resuming right now."] [duration=5.504040075s]`
- OnWorkerOnline of job master `5f5ad64b-1986-4a0a-a088-cf192b3c8d35` is not triggered.

---
Two problem here may be

When worker manger marks ready, `IsMasterReady` will return true, but part of the `OnWorkerOnline` callbacks are not triggered yet.

**Comment by amyangfei** [comment]
`OnWorkerOnline` only triggers with incremental worker(incremental worker means the worker is created by this worker manager).
The master impl should check all worker status when `IsMasterReady` returns true.
